### ISSUE TITLE
need to pubilsh npm

### ISSUE THREAD

**Issue by rohithroshan-r** [henriqpohl/turborepo-tailwindcss-shadcn-ui#1]
how i build the packages

**Comment by henriqpohl** [comment]
Hello @rohithroshan-r, how are you?

If you want to build a single app, follow the steps below:

- Go to the **apps/** directory and choose which app you want and run **`pnpm build`** to build the package you selected.

> for example **`cd apps/your-app`** to enter your application folder and then **`pnpm build`** to build the selected application.

Or if you have many applications and want to build them all at once, go to the **apps/** directory and run **`pnpm build`** to build all your applications within the applications directory.

Let me know if you need more help, ok?

Cheers!

**Comment by rohithroshan-r** [comment]
@henriqpohl thank you dear
