### ISSUE TITLE
Issue with eslint

### ISSUE THREAD

**Issue by MarquesCoding** [henriqpohl/turborepo-tailwindcss-shadcn-ui#2]
![image](https://github.com/user-attachments/assets/a75bd871-8358-4b35-9ba9-cfb33e65ba1a)

I'm trying to run the project using IntelliJ Idea Ultimate, but getting error stating it can't find the config file.

![image](https://github.com/user-attachments/assets/17797c13-752c-4d9f-a75b-efcc2b82f676)

**Comment by MarquesCoding** [comment]
Okay, I've just pulled the latest and ran `pnpm run lint` and it's giving me a bunch of errors. This project needs to be migrated to the latest version of eslint.

**Comment by henriqpohl** [comment]
Hi @MarquesCoding , how are you? Hope you're doing well!

I've released a new version with all the dependency updates. Could you please test it and let me know if this issue has been fixed for you?

Cheers!

**Comment by henriqpohl** [comment]
Hi @MarquesCoding how are you doing? 

I would like to know, did you test again the new release?

Cheers!
